---
apiVersion: v1
kind: Secret
metadata:
  name: ldap-bind-secrets # default for secretRefs.ldapSecretRef
type: Opaque
data:
  # Base64 encoded password for the LDAP bind user.
  reva-ldap-bind-password: XXXXXXXXXXXXX

# If your LDAP secure server is not using a trusted certificate
# features.externalUserManagement.ldap.certTrusted == false
# you need to set your LDAP CA (Certificate Authority) certificate in following secret:

---
apiVersion: v1
kind: Secret
metadata:
  name: ldap-ca # default for secretRefs.ldapCaRef
type: Opaque
data:
  # Base64 encoded certificate of the CA that issued the LDAP server certificate.
  ldap-ca.crt: XXXXXXXXXXXXX
