---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret # default for secretRefs.jwtSecretRef
type: Opaque
data:
  # how to generate: base64 encode a random string (reasonable long and mixed characters)
  # example generation command: `tr -cd '[:alnum:],.' < /dev/urandom | fold -w 50 | head -n 1 | base64`
  jwt-secret: XXXXXXXXXXXXX

---
apiVersion: v1
kind: Secret
metadata:
  name: machine-auth-api-key # default for secretRefs.machineAuthApiKeySecretRef
type: Opaque
data:
  # how to generate: base64 encode a random string (reasonable long and mixed characters)
  # example generation command: `tr -cd '[:alnum:],.' < /dev/urandom | fold -w 50 | head -n 1 | base64`
  machine-auth-api-key: XXXXXXXXXXXXX

---
apiVersion: v1
kind: Secret
metadata:
  name: storage-system # default for secretRefs.storagesystemSecretRef
type: Opaque
data:
  # how to generate: base64 encode a UUID V4
  # example generation command: `cat /proc/sys/kernel/random/uuid | tr -d '\n' | base64`
  user-id: XXXXXXXXXXXXX

  # how to generate: base64 encode a random string (reasonable long and mixed characters)
  # example generation command: `tr -cd '[:alnum:],.' < /dev/urandom | fold -w 50 | head -n 1 | base64`
  api-key: XXXXXXXXXXXXX

---
apiVersion: v1
kind: Secret
metadata:
  name: storage-system-jwt-secret # default for secretRefs.storagesystemJwtSecretRef
type: Opaque
data:
  # how to generate: base64 encode a random string (reasonable long and mixed characters)
  # example generation command: `tr -cd '[:alnum:],.' < /dev/urandom | fold -w 50 | head -n 1 | base64`
  storage-system-jwt-secret: XXXXXXXXXXXXX

---
apiVersion: v1
kind: Secret
metadata:
  name: transfer-secret # default for secretRefs.transferSecretSecretRef
type: Opaque
data:
  # how to generate: base64 encode a random string (reasonable long and mixed characters)
  # example generation command: `tr -cd '[:alnum:],.' < /dev/urandom | fold -w 50 | head -n 1 | base64`
  transfer-secret: XXXXXXXXXXXXX

---
apiVersion: v1
kind: Secret
metadata:
  name: thumbnails-transfer-secret # default for secretRefs.thumbnailsSecretRef
type: Opaque
data:
  # how to generate: base64 encode a random string (reasonable long and mixed characters)
  # example generation command: `tr -cd '[:alnum:],.' < /dev/urandom | fold -w 50 | head -n 1 | base64`
  thumbnails-transfer-secret: XXXXXXXXXXXXX
